### ISSUE TITLE
Socket IO front end script

### ISSUE THREAD

**Issue by teikmeout** [Project-3-Best-Group/reAsk#54]
# Socket IO front end script and Communication

![pleasegod](https://media.giphy.com/media/RoWS9y91dkxG0/giphy.gif)

### Issue Description
This is a shared issue with @smna15:
- [ ] How to put socket io front end script into HTML page after Babel transpiling (dist)
- [ ] How to map and parse `DevTools failed to parse SourceMap: http://localhost:3000/socket.io/socket.io.js.map`

### Things we've tried
- [x] Full socket IO tutorial. Uses static elements and inline script tags. No React
- [x] Can recognize connection on server side, but not on client side. 
- [x] Cannot hard code script into dist index.html file since it recompiles

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@irwintsay

**Comment by rapala61** [comment]
want to chat?

**Comment by teikmeout** [comment]
Yes please @rapala61 

Where should we meet? we came up to the 4th floor

**Comment by rapala61** [comment]
close this please
