### ISSUE TITLE
rendering likes

### ISSUE THREAD

**Issue by mcohen113** [Project-3-Best-Group/reAsk#59]
Having trouble getting likes to render.
-looked at some tutorials online
-went back to "thinking in react" article
-cued up 3 hours ago
-ate lunch, short walk
![screen shot 2016-11-28 at 3 48 35 pm](https://cloud.githubusercontent.com/assets/22035945/20685466/8d90be08-b582-11e6-863d-0dc6be7ebc1a.png)
![screen shot 2016-11-28 at 3 48 11 pm](https://cloud.githubusercontent.com/assets/22035945/20685495/ae5c7262-b582-11e6-96b1-ed0e3dc53cc2.png)

@gittheking @jasonseminara @rapala61 @ @trevorpreston @irwintsay

**Comment by rapala61** [comment]
want to chat?

**Comment by mcohen113** [comment]
sure where you at?

**Comment by rapala61** [comment]
2nd floor

**Comment by mcohen113** [comment]
?

**Comment by rapala61** [comment]
please close

**Comment by mcohen113** [comment]
like logs but put request throws error in console at fetch call in app.jsx
ISSUE NOT RESOLVED
