### ISSUE TITLE
Earlier issue never resolved

### ISSUE THREAD

**Issue by mcohen113** [Project-3-Best-Group/reAsk#65]
Still having trouble getting likes to render
![screen shot 2016-11-28 at 8 04 19 pm](https://cloud.githubusercontent.com/assets/22035945/20692509/7e19f826-b5a6-11e6-98db-04761c657fa2.png)

404 error in console on fetch call from likeQuestion function

@gittheking @rapala61 @jasonseminara @trevorpreston @irwintsay

**Comment by irwintsay** [comment]
Have you looked at that 404 error closely? I'm guessing the problem is that you're hitting a route of '/api/questions/q', but really you want to hit a route of '/api/questions/:id' where :id is the id of the question you're trying to update.
